.PHONY: a b c d e f

a:
	cat data/a.1 | ./a.pl
	cat data/a.2 | ./a.pl
	cat data/a.3 | ./a.pl

b:
	cat data/b.1 | ./b.pl
	cat data/b.2 | ./b.pl
	cat data/b.3 | ./b.pl

c:
	cat data/c.1 | ./c2.pl
	cat data/c.2 | ./c2.pl

d:
	cat data/d.1 | ./d2.pl
	cat data/d.2 | ./d2.pl
	cat data/d.3 | ./d2.pl
	cat data/d.4 | ./d2.pl
	cat data/d.5 | ./d2.pl

e:
	cat data/e.1 | ./e2.pl
	cat data/e.2 | ./e2.pl
	cat data/e.3 | ./e2.pl

f:
	cat data/f.1 | ./f.pl
	cat data/f.2 | ./f.pl
