.PHONY: a b c d

a:
	cat data/a.1 | ./a.pl
	cat data/a.2 | ./a.pl
	cat data/a.3 | ./a.pl

b:
	cat data/b.1 | ./b2.pl
	cat data/b.2 | ./b2.pl
	cat data/b.3 | ./b2.pl
	cat data/b.4 | ./b2.pl

c:
	cat data/c.1 | ./c.pl
	cat data/c.2 | ./c.pl
	cat data/c.3 | ./c.pl

d:
	cat data/d.1  | time ./d.pl
	cat data/d.2  | time ./d.pl
	cat data/d.3  | time ./d.pl
	cat data/d.4  | time ./d.pl
	cat data/d.5  | time ./d.pl
	cat data/d.6  | time ./d.pl
	cat data/d.7  | time ./d.pl
	cat data/d.8  | time ./d.pl
	cat data/d.9  | time ./d.pl
	cat data/d.10 | time ./d.pl
	cat data/d.11 | time ./d.pl

e:
	cat data/e.1 | ./e.pl
	cat data/e.2 | ./e.pl
