[workspace]

members = [
    "334",
    "339",
    "340",
    "341",
    "342",
    "343",
    "344",
    "345",
    "346",
    "training",
    "347",
    "348",
    "349",
    "350",
    "351",
    "352",
    "353",
    "354",
    "355",
]
