.PHONY: a b c d e f

p%:
	@pbcopy <src/bin/$*.rs

a:
	cat data/a.1 | cargo run --bin a
	cat data/a.2 | cargo run --bin a
	cat data/a.3 | cargo run --bin a
	cat data/a.4 | cargo run --bin a

b:
	cat data/b.1 | cargo run --bin b
	cat data/b.2 | cargo run --bin b
	cat data/b.3 | cargo run --bin b

c:
	cat data/c.1 | cargo run --bin c
	cat data/c.2 | cargo run --bin c
	cat data/c.3 | cargo run --bin c

d:
	cat data/d.1 | cargo run --bin d
	cat data/d.2 | cargo run --bin d
	cat data/d.3 | cargo run --bin d
	cat data/d.4 | cargo run --bin d

e:
	cat data/e.1 | cargo run --bin e
	cat data/e.2 | cargo run --bin e

f:
	cat data/f.1 | cargo run --bin f
	cat data/f.2 | cargo run --bin f
