.PHONY: a10 a20 a21 a22 b14 b20 b21

a10:
	cat data/a10.1 | ./a10.pl

a20:
	cat data/a20.1 | ./a20.pl
	cat data/a20.2 | ./a20.pl
	cat data/a20.3 | ./a20.pl

a21:
	cat data/a21.1 | ./a21.pl
	cat data/a21.2 | ./a21.pl

a22:
	cat data/a22.1 | ./a22.pl
	cat data/a22.2 | ./a22.pl

b14:
	cat data/b14.1 | ./b14.pl

b20:
	cat data/b20.1 | ./b20.pl
	cat data/b20.2 | ./b20.pl
	cat data/b20.3 | ./b20.pl

b21:
	cat data/b21.1 | ./b21.pl
	cat data/b21.2 | ./b21.pl
