.PHONY: a10 a20 a21 a22 a24 a25 a26 a29 a30 a32 a34 a35 a38 a40 b14 b20 b21 b23 b24 b26 b27 b30 b32 b33 b34 b37 b38 b39

a10:
	cat data/a10.1 | ./a10.pl

a20:
	cat data/a20.1 | ./a20.pl
	cat data/a20.2 | ./a20.pl
	cat data/a20.3 | ./a20.pl

a21:
	cat data/a21.1 | ./a21.pl
	cat data/a21.2 | ./a21.pl

a22:
	cat data/a22.1 | ./a22.pl
	cat data/a22.2 | ./a22.pl

a23:
	cat data/a23.1 | ./a23.pl
	cat data/a23.2 | ./a23.pl

a24:
	cat data/a24.1 | ./a24.pl
	cat data/a24.2 | ./a24.pl

a25:
	cat data/a25.1 | ./a25.pl
	cat data/a25.2 | ./a25.pl
	cat data/a25.3 | ./a25.pl

a26:
	cat data/a26.1 | ./a26.pl

a29:
	cat data/a29.1 | ./a29.pl
	cat data/a29.2 | ./a29.pl

a30:
	cat data/a30.1 | ./a30.pl
	cat data/a30.2 | ./a30.pl

a32:
	cat data/a32.1 | ./a32.pl
	cat data/a32.2 | ./a32.pl

a33:
	cat data/a33.1 | ./a33.pl
	cat data/a33.2 | ./a33.pl

a34:
#	cat data/a34.1 | ./a34.pl
#	cat data/a34.2 | ./a34.pl
	cat data/a34.3 | ./a34.pl

a35:
	cat data/a35.1 | ./a35.pl

a38:
	cat data/a38.1 | ./a38.pl

a40:
	cat data/a40.1 | ./a40.pl

a39:
	cat data/a39.1 | ./a39.pl

b14:
	cat data/b14.1 | ./b14.pl

b20:
	cat data/b20.1 | ./b20.pl
	cat data/b20.2 | ./b20.pl
	cat data/b20.3 | ./b20.pl

b21:
	cat data/b21.1 | ./b21.pl
	cat data/b21.2 | ./b21.pl

b23:
	cat data/b23.1 | ./b23.pl
	cat data/b23.2 | ./b23.pl

b24:
	cat data/b24.1 | ./b24.pl
	cat data/b24.2 | ./b24.pl

b26:
	cat data/b26.1 | ./b26.pl

b27:
	cat data/b27.1 | ./b27.pl
	cat data/b27.2 | ./b27.pl

b30:
	cat data/b30.1 | ./b30.pl
	cat data/b30.2 | ./b30.pl
	cat data/b30.3 | ./b30.pl

b32:
	cat data/b32.1 | ./b32.pl
	cat data/b32.2 | ./b32.pl
	cat data/b32.3 | ./b32.pl

b33:
	cat data/b33.1 | ./b33.pl
	cat data/b33.2 | ./b33.pl

b34:
	cat data/b34.1 | ./b34.pl
	cat data/b34.2 | ./b34.pl

b37:
	cat data/b37.1 | ./b37.pl
	cat data/b37.2 | ./b37.pl

b38:
	cat data/b38.1 | ./b38.pl

b39:
	cat data/b39.1 | ./b39.pl
