.PHONY: a10 a20 a21 a22 a24 a25 a26 b14 b20 b21 b23 b24 b26

a10:
	cat data/a10.1 | ./a10.pl

a20:
	cat data/a20.1 | ./a20.pl
	cat data/a20.2 | ./a20.pl
	cat data/a20.3 | ./a20.pl

a21:
	cat data/a21.1 | ./a21.pl
	cat data/a21.2 | ./a21.pl

a22:
	cat data/a22.1 | ./a22.pl
	cat data/a22.2 | ./a22.pl

a23:
	cat data/a23.1 | ./a23.pl
	cat data/a23.2 | ./a23.pl

a24:
	cat data/a24.1 | ./a24.pl
	cat data/a24.2 | ./a24.pl

a25:
	cat data/a25.1 | ./a25.pl
	cat data/a25.2 | ./a25.pl
	cat data/a25.3 | ./a25.pl

a26:
	cat data/a26.1 | ./a26.pl

b14:
	cat data/b14.1 | ./b14.pl

b20:
	cat data/b20.1 | ./b20.pl
	cat data/b20.2 | ./b20.pl
	cat data/b20.3 | ./b20.pl

b21:
	cat data/b21.1 | ./b21.pl
	cat data/b21.2 | ./b21.pl

b23:
	cat data/b23.1 | ./b23.pl
	cat data/b23.2 | ./b23.pl

b24:
	cat data/b24.1 | ./b24.pl
	cat data/b24.2 | ./b24.pl

b26:
	cat data/b26.1 | ./b26.pl
