BIN_DIR = bin

$(BIN_DIR)/%: %.rs
	rustc --out-dir $(BIN_DIR) $<

p%:
	@pbcopy <$*.rs

a41: $(BIN_DIR)/a41
	cat data/a41.1 | $(BIN_DIR)/a41
	cat data/a41.2 | $(BIN_DIR)/a41

a42: $(BIN_DIR)/a42
	cat data/a42.1 | $(BIN_DIR)/a42

a43: $(BIN_DIR)/a43
	cat data/a43.1 | $(BIN_DIR)/a43

a44: $(BIN_DIR)/a44
	cat data/a44.1 | $(BIN_DIR)/a44

a45: $(BIN_DIR)/a45
	cat data/a45.1 | $(BIN_DIR)/a45

a46: $(BIN_DIR)/a46
	cat data/a46.1 | $(BIN_DIR)/a46

a56: $(BIN_DIR)/a56
	cat data/a56.1 | $(BIN_DIR)/a56

a57: $(BIN_DIR)/a57
	cat data/a57.1 | $(BIN_DIR)/a57
	cat data/a57.2 | $(BIN_DIR)/a57

a58: $(BIN_DIR)/a58
	cat data/a58.0 | $(BIN_DIR)/a58
	cat data/a58.1 | $(BIN_DIR)/a58
	cat data/a58.2 | $(BIN_DIR)/a58

a59: $(BIN_DIR)/a59
	cat data/a59.1 | $(BIN_DIR)/a59

a60: $(BIN_DIR)/a60_2
	cat data/a60.1 | $(BIN_DIR)/a60_2

a61: $(BIN_DIR)/a61
	cat data/a61.1 | $(BIN_DIR)/a61
	cat data/a61.2 | $(BIN_DIR)/a61

a62: $(BIN_DIR)/a62
	cat data/a62.1 | $(BIN_DIR)/a62
	cat data/a62.2 | $(BIN_DIR)/a62

a63: $(BIN_DIR)/a63
	cat data/a63.1 | $(BIN_DIR)/a63
	cat data/a63.2 | $(BIN_DIR)/a63

a64: $(BIN_DIR)/a64
	cat data/a64.1 | $(BIN_DIR)/a64
	cat data/a64.2 | $(BIN_DIR)/a64

a65: $(BIN_DIR)/a65
	cat data/a65.1 | $(BIN_DIR)/a65
	cat data/a65.2 | $(BIN_DIR)/a65

a66: $(BIN_DIR)/a66
	cat data/a66.1 | $(BIN_DIR)/a66
	cat data/a66.2 | $(BIN_DIR)/a66

a67: $(BIN_DIR)/a67
	cat data/a67.1 | $(BIN_DIR)/a67

a68: $(BIN_DIR)/a68
	cat data/a68.1 | $(BIN_DIR)/a68

a70: $(BIN_DIR)/a70
	cat data/a70.1 | $(BIN_DIR)/a70
	cat data/a70.2 | $(BIN_DIR)/a70

a71: $(BIN_DIR)/a71
	cat data/a71.1 | $(BIN_DIR)/a71

a72: $(BIN_DIR)/a72
	cat data/a72.1 | $(BIN_DIR)/a72
	cat data/a72.2 | $(BIN_DIR)/a72
	cat data/a72.3 | $(BIN_DIR)/a72

a73: $(BIN_DIR)/a73
	cat data/a73.1 | $(BIN_DIR)/a73

a74: $(BIN_DIR)/a74
	cat data/a74.1 | $(BIN_DIR)/a74

a76: $(BIN_DIR)/a76
	cat data/a76.1 | $(BIN_DIR)/a76

b41: $(BIN_DIR)/b41
	cat data/b41.1 | $(BIN_DIR)/b41
	cat data/b41.2 | $(BIN_DIR)/b41

b42: $(BIN_DIR)/b42
	cat data/b42.1 | $(BIN_DIR)/b42

b43: $(BIN_DIR)/b43
	cat data/b43.1 | $(BIN_DIR)/b43

b44: $(BIN_DIR)/b44
	cat data/b44.1 | $(BIN_DIR)/b44
	cat data/b44.2 | $(BIN_DIR)/b44

b45: $(BIN_DIR)/b45
	cat data/b45.1 | $(BIN_DIR)/b45

b51: $(BIN_DIR)/b51
	cat data/b51.1 | $(BIN_DIR)/b51

b52: $(BIN_DIR)/b52
	cat data/b52.1 | $(BIN_DIR)/b52

b54: $(BIN_DIR)/b54
	cat data/b54.1 | $(BIN_DIR)/b54

b57: $(BIN_DIR)/b57
	cat data/b57.0 | $(BIN_DIR)/b57
	cat data/b57.1 | $(BIN_DIR)/b57

b58: $(BIN_DIR)/b58
	cat data/b58.1 | $(BIN_DIR)/b58

b59: $(BIN_DIR)/b59
	cat data/b59.1 | $(BIN_DIR)/b59
	cat data/b59.2 | $(BIN_DIR)/b59

b61: $(BIN_DIR)/b61
	cat data/b61.1 | $(BIN_DIR)/b61
	cat data/b61.2 | $(BIN_DIR)/b61

b62: $(BIN_DIR)/b62
	cat data/b62.1 | $(BIN_DIR)/b62
	cat data/b62.2 | $(BIN_DIR)/b62

b63: $(BIN_DIR)/b63
	cat data/b63.1 | $(BIN_DIR)/b63
	cat data/b63.2 | $(BIN_DIR)/b63
	cat data/b63.3 | $(BIN_DIR)/b63

b64: $(BIN_DIR)/b64
	cat data/b64.1 | $(BIN_DIR)/b64
	cat data/b64.2 | $(BIN_DIR)/b64

b65: $(BIN_DIR)/b65
	cat data/b65.1 | $(BIN_DIR)/b65
	cat data/b65.2 | $(BIN_DIR)/b65

b66: $(BIN_DIR)/b66
	cat data/b66.1 | $(BIN_DIR)/b66
	cat data/b66.2 | $(BIN_DIR)/b66
	cat data/b66.3 | $(BIN_DIR)/b66

b67: $(BIN_DIR)/b67
	cat data/b67.1 | $(BIN_DIR)/b67

c1: $(BIN_DIR)/c1
	cat data/c1.1 | $(BIN_DIR)/c1

c2: $(BIN_DIR)/c2
	cat data/c2.1 | $(BIN_DIR)/c2
	cat data/c2.2 | $(BIN_DIR)/c2

c3: $(BIN_DIR)/c3
	cat data/c3.1 | $(BIN_DIR)/c3

c4: $(BIN_DIR)/c4
	cat data/c4.1 | $(BIN_DIR)/c4
	cat data/c4.2 | $(BIN_DIR)/c4

c5: $(BIN_DIR)/c5
	cat data/c5.1 | $(BIN_DIR)/c5

c6: $(BIN_DIR)/c6
	cat data/c6.1 | $(BIN_DIR)/c6

c7: $(BIN_DIR)/c7
	cat data/c7.1 | $(BIN_DIR)/c7
	cat data/c7.2 | $(BIN_DIR)/c7

c8: $(BIN_DIR)/c8
	cat data/c8.1 | $(BIN_DIR)/c8
	cat data/c8.2 | $(BIN_DIR)/c8
	cat data/c8.3 | $(BIN_DIR)/c8

c9: $(BIN_DIR)/c9
	cat data/c9.1 | $(BIN_DIR)/c9