.PHONY: a b c d e f

a:
	cat data/a.1 | ./a.pl
	cat data/a.2 | ./a.pl
	cat data/a.3 | ./a.pl

b:
	cat data/b.1 | ./b.pl
	cat data/b.2 | ./b.pl
	cat data/b.3 | ./b.pl
	cat data/b.4 | ./b.pl
	cat data/b.5 | ./b.pl

c:
	cat data/c.1 | ./c.pl
	cat data/c.2 | ./c.pl
	cat data/c.3 | ./c.pl

d:
	cat data/d.1 | ./d.pl
	cat data/d.2 | ./d.pl

e:
	cat data/e.1 | time ./e2.pl
	cat data/e.2 | time ./e2.pl
	cat data/e.3 | time ./e2.pl
	cat data/e.4 | time ./e2.pl

f:
	cat data/f.1 | ./f.pl
	cat data/f.2 | ./f.pl
