.PHONY: a b c d

a:
	cat data/a.1 | ./a.pl
	cat data/a.2 | ./a.pl

b:
	cat data/b.1 | ./b.pl
	cat data/b.2 | ./b.pl
	cat data/b.3 | ./b.pl

c:
	cat data/c.1 | ./c.pl
	cat data/c.2 | ./c.pl
	cat data/c.3 | ./c.pl

d:
	cat data/d.1 | ./d.pl
	cat data/d.2 | ./d.pl
	cat data/d.3 | ./d.pl

e:
	cat data/e.1 | ./e.pl
	cat data/e.2 | ./e.pl
