p%:
	@pbcopy <src/bin/$*.rs

RELEASE=

228c:
	cat data/228c.1 | cargo run $(RELEASE) --bin 228c
	cat data/228c.2 | cargo run $(RELEASE) --bin 228c
	cat data/228c.3 | cargo run $(RELEASE) --bin 228c
	cat data/228c.4 | cargo run $(RELEASE) --bin 228c

233c:
	cat data/233c.1 | cargo run $(RELEASE) --bin 233c
	cat data/233c.2 | cargo run $(RELEASE) --bin 233c
	cat data/233c.3 | cargo run $(RELEASE) --bin 233c

245c:
	cat data/245c.1 | cargo run $(RELEASE) --bin 245c
	cat data/245c.2 | cargo run $(RELEASE) --bin 245c
	cat data/245c.3 | cargo run $(RELEASE) --bin 245c

285d:
	cat data/285d.1 | cargo run $(RELEASE) --bin 285d
	cat data/285d.2 | cargo run $(RELEASE) --bin 285d
	cat data/285d.3 | cargo run $(RELEASE) --bin 285d

287d:
	cat data/287d.1 | cargo run $(RELEASE) --bin 287d
	cat data/287d.2 | cargo run $(RELEASE) --bin 287d
	cat data/287d.3 | cargo run $(RELEASE) --bin 287d
	cat data/287d.4 | cargo run $(RELEASE) --bin 287d

301c:
	cat data/301c.1 | cargo run $(RELEASE) --bin 301c
	cat data/301c.2 | cargo run $(RELEASE) --bin 301c
	cat data/301c.3 | cargo run $(RELEASE) --bin 301c
	cat data/301c.4 | cargo run $(RELEASE) --bin 301c

311d:
	cat data/311d.1 | cargo run $(RELEASE) --bin 311d
	cat data/311d.2 | cargo run $(RELEASE) --bin 311d

333c:
	cat data/333c.1 | cargo run $(RELEASE) --bin 333c
	cat data/333c.2 | cargo run $(RELEASE) --bin 333c
	cat data/333c.3 | cargo run $(RELEASE) --bin 333c

342c:
	cat data/342c.1 | cargo run $(RELEASE) --bin 342c
	cat data/342c.2 | cargo run $(RELEASE) --bin 342c
	cat data/342c.3 | cargo run $(RELEASE) --bin 342c
	cat data/342c.4 | cargo run $(RELEASE) --bin 342c

t1:
	cat data/t1.1 | cargo run $(RELEASE) --bin t1

t2:
	cat data/t2.1 | cargo run $(RELEASE) --bin t2

t3:
	cat data/t3.1 | cargo run $(RELEASE) --bin t3

t4:
	cat data/t4.1 | cargo run $(RELEASE) --bin t4

t5:
	cat data/t5.1 | cargo run $(RELEASE) --bin t5

t6:
	cat data/t6.1 | cargo run $(RELEASE) --bin t6
