p%:
	@pbcopy <src/bin/$*.rs

RELEASE=

228c:
	cat data/228c.1 | cargo run $(RELEASE) --bin 228c
	cat data/228c.2 | cargo run $(RELEASE) --bin 228c
	cat data/228c.3 | cargo run $(RELEASE) --bin 228c
	cat data/228c.4 | cargo run $(RELEASE) --bin 228c

245c:
	cat data/245c.1 | cargo run $(RELEASE) --bin 245c
	cat data/245c.2 | cargo run $(RELEASE) --bin 245c
	cat data/245c.3 | cargo run $(RELEASE) --bin 245c

285d:
	cat data/285d.1 | cargo run $(RELEASE) --bin 285d
	cat data/285d.2 | cargo run $(RELEASE) --bin 285d
	cat data/285d.3 | cargo run $(RELEASE) --bin 285d

311d:
	cat data/311d.1 | cargo run $(RELEASE) --bin 311d
	cat data/311d.2 | cargo run $(RELEASE) --bin 311d

333c:
	cat data/333c.1 | cargo run $(RELEASE) --bin 333c
	cat data/333c.2 | cargo run $(RELEASE) --bin 333c
	cat data/333c.3 | cargo run $(RELEASE) --bin 333c
