p%:
	@pbcopy <src/bin/$*.rs

RELEASE=

285d:
	cat data/285d.1 | cargo run $(RELEASE) --bin 285d
	cat data/285d.2 | cargo run $(RELEASE) --bin 285d
	cat data/285d.3 | cargo run $(RELEASE) --bin 285d

311d:
	cat data/311d.1 | cargo run $(RELEASE) --bin 311d
	cat data/311d.2 | cargo run $(RELEASE) --bin 311d
