.PHONY: a b c d

a:
	cat a.data.1 | ./a.pl
	cat a.data.2 | ./a.pl

b:
	cat b.data.1 | ./b.pl
	cat b.data.2 | ./b.pl

c:
	cat c.data.1 | ./c.pl
	cat c.data.2 | ./c.pl

d:
	cat d.data.1 | ./d.pl
	cat d.data.2 | ./d.pl

e:
	cat e.data.1 | ./e.pl
