#!/usr/bin/env perl
use 5.10.0;
use utf8;
use strict;
use warnings;
use open qw( :utf8 :std );
use Data::Dumper;

for my $arg ( @ARGV ) {
    my @factors = get_factors( $arg );
    say $arg, q{: }, join q{ }, @factors;
}


exit;

sub get_factors {
    my $value = shift;

    my $n = $value;
    my @results = ( );

    for ( my $i = 2; $i * $i <= $value; ++$i ) {
        until ( $n % $i ) {
            push @results, $i;
            $n = int( $n / $i );
        }
    }

    push @results, $n
        unless $n == 1;

    return @results;
}
